version: '3.4'

services:
  middt_sample_blazorserver:
    image: ${DOCKER_REGISTRY-}middtsampleblazorserver
    build:
      context: .
      dockerfile: Sample/Middt.Sample.BlazorServer/Dockerfile
    depends_on: [middt_sample_api]

  middt_sample_api:
    image: ${DOCKER_REGISTRY-}middtsampleapi
    build:
      context: .
      dockerfile: Sample/Middt.Sample.Api/Dockerfile

  mq:
    image: "rabbitmq:3.9-management"    
    ports:
      - "5672:5672"
      - "15672:15672"

  redis_master:
    image: "redis:latest"
    ports:
      - "6379:6379" 

  db_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_TCP_PORT=1433
    volumes:
      - ./data:/scripts/
    ports:
      - "1433:1433"
    #entrypoint: /bin/bash
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        pid=$$!

        echo "Waiting for MS SQL to be available"
        /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
        is_up=$$?
        while [ $$is_up -ne 0 ] ; do
          echo -e $$(date)
          /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
          is_up=$$?
          sleep 5
        done

        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -l 30 -e -i $$foo
        done
        echo "All scripts have been executed. Waiting for MS SQL(pid $$pid) to terminate."

        wait $$pid
